// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mptc.dgc.sample.infrastructure.Models;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}