// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mptc.dgc.sample.infrastructure.Models;

public partial class Certificate
{
    public int Id { get; set; }

    public Guid UniversityId { get; set; }

    public string StudentId { get; set; }

    public string Number { get; set; }

    public string NameKh { get; set; }

    public string NameEn { get; set; }

    public string Degree { get; set; }

    public string DegreeKm { get; set; }

    public string Year { get; set; }

    public string NationalId { get; set; }

    public string Passport { get; set; }

    public Guid CertificateOaGuid { get; set; }

    public string RawDataJson { get; set; }

    public string WrapContent { get; set; }

    public bool IsCertificateProduced { get; set; }

    public string CertificateVerifyUrl { get; set; }

    public string CertificatePdfUrl { get; set; }

    public string CertificateOadecryptKey { get; set; }

    public bool IsSignedWithBlockchain { get; set; }

    public string TargetHash { get; set; }

    public string MerkleRoot { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual University University { get; set; }
}