// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mptc.dgc.sample.infrastructure.Models;

public partial class Item
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int CategoryId { get; set; }

    public decimal Price { get; set; }

    public bool IsAvailable { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public virtual Category Category { get; set; }
}