// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace mptc.dgc.sample.infrastructure.Models;

public partial class SampleContext : DbContext
{
    public SampleContext(DbContextOptions<SampleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Certificate> Certificates { get; set; }

    public virtual DbSet<University> Universities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Certificate>(entity =>
        {
            entity.ToTable("Certificate");

            entity.Property(e => e.CertificateOadecryptKey).HasColumnName("CertificateOADecryptKey");
            entity.Property(e => e.CertificatePdfUrl).HasMaxLength(500);
            entity.Property(e => e.CertificateVerifyUrl).HasMaxLength(500);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Degree).HasMaxLength(255);
            entity.Property(e => e.DegreeKm).HasMaxLength(255);
            entity.Property(e => e.MerkleRoot).HasMaxLength(500);
            entity.Property(e => e.NameEn).HasMaxLength(255);
            entity.Property(e => e.NameKh)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NationalId).HasMaxLength(50);
            entity.Property(e => e.Number).HasMaxLength(50);
            entity.Property(e => e.Passport).HasMaxLength(50);
            entity.Property(e => e.StudentId).HasMaxLength(50);
            entity.Property(e => e.TargetHash).HasMaxLength(500);
            entity.Property(e => e.Year).HasMaxLength(50);

            entity.HasOne(d => d.University).WithMany(p => p.Certificates)
                .HasForeignKey(d => d.UniversityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Certificate_University");
        });

        modelBuilder.Entity<University>(entity =>
        {
            entity.ToTable("University");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).IsRequired();
            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogoUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.NameKh).HasMaxLength(150);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}