// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mptc.dgc.sample.infrastructure.Models;

public partial class University
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string NameKh { get; set; }

    public string ContactName { get; set; }

    public string Address { get; set; }

    public bool IsActive { get; set; }

    public string LogoUrl { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();
}